-- Add new categories for gaming and app-store products
insert into public.categories (name, slug, image_url)
values
  ('Gaming Top-Ups', 'gaming-top-ups', '/products/category-gaming-topups.svg'),
  ('Gaming Gift Cards', 'gaming-gift-cards', '/products/category-gaming-giftcards.svg'),
  ('App Store Cards', 'app-store-cards', '/products/category-app-store-cards.svg')
on conflict (slug) do update set name = excluded.name, image_url = excluded.image_url;

with category_ids as (
  select id, slug from public.categories
)
insert into public.products (
  name, slug, category_id, price_dt, short_description, long_description,
  delivery_time, requirements, refund_policy, is_featured, image_url
)
values
  -- Fortnite V-Bucks (Gaming Top-Ups)
  ('Fortnite 1000 V-Bucks', 'fortnite-vbucks-1000', (select id from category_ids where slug = 'gaming-top-ups'), 30,
   '1000 Fortnite V-Bucks top-up.',
   'Buy 1000 Fortnite V-Bucks to unlock skins, battle passes and exclusive in-game items.',
   'Instant / 5-15 min',
   'Share your Epic Games ID or account email for safe delivery.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/fortnite-vbucks.svg'
  ),
  ('Fortnite 2800 V-Bucks', 'fortnite-vbucks-2800', (select id from category_ids where slug = 'gaming-top-ups'), 75,
   '2800 Fortnite V-Bucks top-up.',
   'Buy 2800 Fortnite V-Bucks to unlock skins, battle passes and exclusive in-game items.',
   'Instant / 5-15 min',
   'Share your Epic Games ID or account email for safe delivery.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/fortnite-vbucks.svg'
  ),
  ('Fortnite 5000 V-Bucks', 'fortnite-vbucks-5000', (select id from category_ids where slug = 'gaming-top-ups'), 125,
   '5000 Fortnite V-Bucks top-up.',
   'Buy 5000 Fortnite V-Bucks to unlock skins, battle passes and exclusive in-game items.',
   'Instant / 5-20 min',
   'Share your Epic Games ID or account email for safe delivery.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/fortnite-vbucks.svg'
  ),
  ('Fortnite 13500 V-Bucks', 'fortnite-vbucks-13500', (select id from category_ids where slug = 'gaming-top-ups'), 290,
   '13500 Fortnite V-Bucks top-up.',
   'Buy 13500 Fortnite V-Bucks to unlock skins, battle passes and exclusive in-game items.',
   'Instant / 5-20 min',
   'Share your Epic Games ID or account email for safe delivery.',
   'Refund only if top-up is not delivered.',
   true,
   '/products/fortnite-vbucks.svg'
  ),

  -- Roblox Robux (Gaming Top-Ups)
  ('Roblox 400 Robux', 'roblox-robux-400', (select id from category_ids where slug = 'gaming-top-ups'), 20,
   '400 Robux top-up for Roblox.',
   'Get 400 Robux to purchase items, accessories and upgrades in Roblox games.',
   'Instant / 5-15 min',
   'Provide your Roblox username for secure delivery.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/roblox-robux.svg'
  ),
  ('Roblox 800 Robux', 'roblox-robux-800', (select id from category_ids where slug = 'gaming-top-ups'), 35,
   '800 Robux top-up for Roblox.',
   'Get 800 Robux to purchase items, accessories and upgrades in Roblox games.',
   'Instant / 5-15 min',
   'Provide your Roblox username for secure delivery.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/roblox-robux.svg'
  ),
  ('Roblox 1200 Robux', 'roblox-robux-1200', (select id from category_ids where slug = 'gaming-top-ups'), 50,
   '1200 Robux top-up for Roblox.',
   'Get 1200 Robux to purchase items, accessories and upgrades in Roblox games.',
   'Instant / 5-20 min',
   'Provide your Roblox username for secure delivery.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/roblox-robux.svg'
  ),
  ('Roblox 2000 Robux', 'roblox-robux-2000', (select id from category_ids where slug = 'gaming-top-ups'), 80,
   '2000 Robux top-up for Roblox.',
   'Get 2000 Robux to purchase items, accessories and upgrades in Roblox games.',
   'Instant / 5-20 min',
   'Provide your Roblox username for secure delivery.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/roblox-robux.svg'
  ),
  ('Roblox 4500 Robux', 'roblox-robux-4500', (select id from category_ids where slug = 'gaming-top-ups'), 160,
   '4500 Robux top-up for Roblox.',
   'Get 4500 Robux to purchase items, accessories and upgrades in Roblox games.',
   'Instant / 5-20 min',
   'Provide your Roblox username for secure delivery.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/roblox-robux.svg'
  ),
  ('Roblox 10000 Robux', 'roblox-robux-10000', (select id from category_ids where slug = 'gaming-top-ups'), 320,
   '10000 Robux top-up for Roblox.',
   'Get 10000 Robux to purchase items, accessories and upgrades in Roblox games.',
   'Instant / 5-20 min',
   'Provide your Roblox username for secure delivery.',
   'Refund only if top-up is not delivered.',
   true,
   '/products/roblox-robux.svg'
  ),

  -- PUBG Mobile UC (Gaming Top-Ups)
  ('PUBG Mobile 60 UC', 'pubg-uc-60', (select id from category_ids where slug = 'gaming-top-ups'), 10,
   '60 UC top-up for PUBG Mobile.',
   'Recharge 60 UC in PUBG Mobile to unlock skins, weapons and battle passes.',
   'Instant / 5-15 min',
   'Provide your PUBG Mobile ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/pubg-uc.svg'
  ),
  ('PUBG Mobile 325 UC', 'pubg-uc-325', (select id from category_ids where slug = 'gaming-top-ups'), 40,
   '325 UC top-up for PUBG Mobile.',
   'Recharge 325 UC in PUBG Mobile to unlock skins, weapons and battle passes.',
   'Instant / 5-15 min',
   'Provide your PUBG Mobile ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/pubg-uc.svg'
  ),
  ('PUBG Mobile 660 UC', 'pubg-uc-660', (select id from category_ids where slug = 'gaming-top-ups'), 75,
   '660 UC top-up for PUBG Mobile.',
   'Recharge 660 UC in PUBG Mobile to unlock skins, weapons and battle passes.',
   'Instant / 5-20 min',
   'Provide your PUBG Mobile ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/pubg-uc.svg'
  ),
  ('PUBG Mobile 1800 UC', 'pubg-uc-1800', (select id from category_ids where slug = 'gaming-top-ups'), 190,
   '1800 UC top-up for PUBG Mobile.',
   'Recharge 1800 UC in PUBG Mobile to unlock skins, weapons and battle passes.',
   'Instant / 5-20 min',
   'Provide your PUBG Mobile ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/pubg-uc.svg'
  ),
  ('PUBG Mobile 3850 UC', 'pubg-uc-3850', (select id from category_ids where slug = 'gaming-top-ups'), 380,
   '3850 UC top-up for PUBG Mobile.',
   'Recharge 3850 UC in PUBG Mobile to unlock skins, weapons and battle passes.',
   'Instant / 5-20 min',
   'Provide your PUBG Mobile ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   true,
   '/products/pubg-uc.svg'
  ),

  -- Free Fire Diamonds (Gaming Top-Ups)
  ('Free Fire 100 Diamonds', 'freefire-diamonds-100', (select id from category_ids where slug = 'gaming-top-ups'), 10,
   '100 diamonds top-up for Free Fire.',
   'Buy 100 Free Fire diamonds to unlock skins, characters and special items.',
   'Instant / 5-15 min',
   'Provide your Free Fire ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/freefire-diamonds.svg'
  ),
  ('Free Fire 310 Diamonds', 'freefire-diamonds-310', (select id from category_ids where slug = 'gaming-top-ups'), 30,
   '310 diamonds top-up for Free Fire.',
   'Buy 310 Free Fire diamonds to unlock skins, characters and special items.',
   'Instant / 5-15 min',
   'Provide your Free Fire ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/freefire-diamonds.svg'
  ),
  ('Free Fire 520 Diamonds', 'freefire-diamonds-520', (select id from category_ids where slug = 'gaming-top-ups'), 50,
   '520 diamonds top-up for Free Fire.',
   'Buy 520 Free Fire diamonds to unlock skins, characters and special items.',
   'Instant / 5-20 min',
   'Provide your Free Fire ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/freefire-diamonds.svg'
  ),
  ('Free Fire 1060 Diamonds', 'freefire-diamonds-1060', (select id from category_ids where slug = 'gaming-top-ups'), 95,
   '1060 diamonds top-up for Free Fire.',
   'Buy 1060 Free Fire diamonds to unlock skins, characters and special items.',
   'Instant / 5-20 min',
   'Provide your Free Fire ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   true,
   '/products/freefire-diamonds.svg'
  ),

  -- Valorant Points (Gaming Top-Ups)
  ('Valorant 120 VP', 'valorant-points-120', (select id from category_ids where slug = 'gaming-top-ups'), 15,
   '120 Valorant Points top-up.',
   'Recharge 120 VP to buy weapon skins, bundles and battle passes in Valorant.',
   'Instant / 5-15 min',
   'Provide your Riot ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/valorant-points.svg'
  ),
  ('Valorant 250 VP', 'valorant-points-250', (select id from category_ids where slug = 'gaming-top-ups'), 25,
   '250 Valorant Points top-up.',
   'Recharge 250 VP to buy weapon skins, bundles and battle passes in Valorant.',
   'Instant / 5-15 min',
   'Provide your Riot ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/valorant-points.svg'
  ),
  ('Valorant 500 VP', 'valorant-points-500', (select id from category_ids where slug = 'gaming-top-ups'), 45,
   '500 Valorant Points top-up.',
   'Recharge 500 VP to buy weapon skins, bundles and battle passes in Valorant.',
   'Instant / 5-20 min',
   'Provide your Riot ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/valorant-points.svg'
  ),
  ('Valorant 1100 VP', 'valorant-points-1100', (select id from category_ids where slug = 'gaming-top-ups'), 90,
   '1100 Valorant Points top-up.',
   'Recharge 1100 VP to buy weapon skins, bundles and battle passes in Valorant.',
   'Instant / 5-20 min',
   'Provide your Riot ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   false,
   '/products/valorant-points.svg'
  ),
  ('Valorant 2250 VP', 'valorant-points-2250', (select id from category_ids where slug = 'gaming-top-ups'), 175,
   '2250 Valorant Points top-up.',
   'Recharge 2250 VP to buy weapon skins, bundles and battle passes in Valorant.',
   'Instant / 5-20 min',
   'Provide your Riot ID for safe top-up.',
   'Refund only if top-up is not delivered.',
   true,
   '/products/valorant-points.svg'
  ),

  -- Steam Gift Cards (Gaming Gift Cards)
  ('Steam Gift Card $5', 'steam-gift-5', (select id from category_ids where slug = 'gaming-gift-cards'), 25,
   'Steam wallet gift card $5.',
   'Add funds to your Steam wallet and purchase games, DLCs and in-game items.',
   'Instant / 5-15 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/steam-giftcard.svg'
  ),
  ('Steam Gift Card $10', 'steam-gift-10', (select id from category_ids where slug = 'gaming-gift-cards'), 50,
   'Steam wallet gift card $10.',
   'Add funds to your Steam wallet and purchase games, DLCs and in-game items.',
   'Instant / 5-15 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/steam-giftcard.svg'
  ),
  ('Steam Gift Card $20', 'steam-gift-20', (select id from category_ids where slug = 'gaming-gift-cards'), 95,
   'Steam wallet gift card $20.',
   'Add funds to your Steam wallet and purchase games, DLCs and in-game items.',
   'Instant / 5-20 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/steam-giftcard.svg'
  ),
  ('Steam Gift Card $50', 'steam-gift-50', (select id from category_ids where slug = 'gaming-gift-cards'), 230,
   'Steam wallet gift card $50.',
   'Add funds to your Steam wallet and purchase games, DLCs and in-game items.',
   'Instant / 5-20 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   true,
   '/products/steam-giftcard.svg'
  ),

  -- PlayStation Network Cards (Gaming Gift Cards)
  ('PlayStation Card $10', 'psn-card-10', (select id from category_ids where slug = 'gaming-gift-cards'), 50,
   'PlayStation Network wallet card $10.',
   'Recharge your PlayStation wallet to buy games, subscriptions and DLC.',
   'Instant / 5-15 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/psn-giftcard.svg'
  ),
  ('PlayStation Card $20', 'psn-card-20', (select id from category_ids where slug = 'gaming-gift-cards'), 95,
   'PlayStation Network wallet card $20.',
   'Recharge your PlayStation wallet to buy games, subscriptions and DLC.',
   'Instant / 5-15 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/psn-giftcard.svg'
  ),
  ('PlayStation Card $50', 'psn-card-50', (select id from category_ids where slug = 'gaming-gift-cards'), 230,
   'PlayStation Network wallet card $50.',
   'Recharge your PlayStation wallet to buy games, subscriptions and DLC.',
   'Instant / 5-20 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/psn-giftcard.svg'
  ),
  ('PlayStation Card $100', 'psn-card-100', (select id from category_ids where slug = 'gaming-gift-cards'), 450,
   'PlayStation Network wallet card $100.',
   'Recharge your PlayStation wallet to buy games, subscriptions and DLC.',
   'Instant / 5-20 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   true,
   '/products/psn-giftcard.svg'
  ),

  -- Xbox Gift Cards (Gaming Gift Cards)
  ('Xbox Gift Card $10', 'xbox-gift-10', (select id from category_ids where slug = 'gaming-gift-cards'), 50,
   'Xbox gift card $10.',
   'Top up your Xbox account to purchase games and subscriptions.',
   'Instant / 5-15 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/xbox-giftcard.svg'
  ),
  ('Xbox Gift Card $25', 'xbox-gift-25', (select id from category_ids where slug = 'gaming-gift-cards'), 120,
   'Xbox gift card $25.',
   'Top up your Xbox account to purchase games and subscriptions.',
   'Instant / 5-15 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/xbox-giftcard.svg'
  ),
  ('Xbox Gift Card $50', 'xbox-gift-50', (select id from category_ids where slug = 'gaming-gift-cards'), 230,
   'Xbox gift card $50.',
   'Top up your Xbox account to purchase games and subscriptions.',
   'Instant / 5-20 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   true,
   '/products/xbox-giftcard.svg'
  ),

  -- Google Play Gift Cards (App Store Cards)
  ('Google Play Gift Card $5', 'googleplay-gift-5', (select id from category_ids where slug = 'app-store-cards'), 25,
   'Google Play gift card $5.',
   'Recharge your Google Play balance to buy apps, games and subscriptions.',
   'Instant / 5-15 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/googleplay-giftcard.svg'
  ),
  ('Google Play Gift Card $10', 'googleplay-gift-10', (select id from category_ids where slug = 'app-store-cards'), 50,
   'Google Play gift card $10.',
   'Recharge your Google Play balance to buy apps, games and subscriptions.',
   'Instant / 5-15 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/googleplay-giftcard.svg'
  ),
  ('Google Play Gift Card $20', 'googleplay-gift-20', (select id from category_ids where slug = 'app-store-cards'), 95,
   'Google Play gift card $20.',
   'Recharge your Google Play balance to buy apps, games and subscriptions.',
   'Instant / 5-20 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/googleplay-giftcard.svg'
  ),
  ('Google Play Gift Card $50', 'googleplay-gift-50', (select id from category_ids where slug = 'app-store-cards'), 230,
   'Google Play gift card $50.',
   'Recharge your Google Play balance to buy apps, games and subscriptions.',
   'Instant / 5-20 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   true,
   '/products/googleplay-giftcard.svg'
  ),

  -- Apple iTunes Gift Cards (App Store Cards)
  ('Apple iTunes Gift Card $10', 'itunes-gift-10', (select id from category_ids where slug = 'app-store-cards'), 50,
   'Apple iTunes gift card $10.',
   'Add funds to your Apple account to purchase apps, games and media.',
   'Instant / 5-15 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/itunes-giftcard.svg'
  ),
  ('Apple iTunes Gift Card $25', 'itunes-gift-25', (select id from category_ids where slug = 'app-store-cards'), 120,
   'Apple iTunes gift card $25.',
   'Add funds to your Apple account to purchase apps, games and media.',
   'Instant / 5-15 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/itunes-giftcard.svg'
  ),
  ('Apple iTunes Gift Card $50', 'itunes-gift-50', (select id from category_ids where slug = 'app-store-cards'), 230,
   'Apple iTunes gift card $50.',
   'Add funds to your Apple account to purchase apps, games and media.',
   'Instant / 5-20 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   false,
   '/products/itunes-giftcard.svg'
  ),
  ('Apple iTunes Gift Card $100', 'itunes-gift-100', (select id from category_ids where slug = 'app-store-cards'), 450,
   'Apple iTunes gift card $100.',
   'Add funds to your Apple account to purchase apps, games and media.',
   'Instant / 5-20 min',
   'You will receive a secure digital code.',
   'No refund after a valid code is delivered.',
   true,
   '/products/itunes-giftcard.svg'
  )
on conflict (slug) do update
set
  name = excluded.name,
  category_id = excluded.category_id,
  price_dt = excluded.price_dt,
  short_description = excluded.short_description,
  long_description = excluded.long_description,
  delivery_time = excluded.delivery_time,
  requirements = excluded.requirements,
  refund_policy = excluded.refund_policy,
  is_featured = excluded.is_featured,
  image_url = excluded.image_url;

